ignorePatterns:
  - "/node_modules/"
  - "**/node_modules/"

extends:
  - "eslint:recommended"
  - "next/core-web-vitals"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"

plugins:
  - "@typescript-eslint"
  - "simple-import-sort"

parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"
  project: "./tsconfig.json"
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: "detect"
  import/resolver:
    typescript:
      project: "./tsconfig.json"

globals:
  dataLayer: true

env:
  "browser": true
  "node": true
  "es2022": true

rules:
  # typescript-eslint
  "@typescript-eslint/restrict-template-expressions": "off"
  "@typescript-eslint/no-unsafe-member-access": "off"

  # import relations
  "simple-import-sort/imports": "error"
  "simple-import-sort/exports": "error"

  # React
  "react/prop-types": "off"
  "react/jsx-uses-react": "off"
  "react/react-in-jsx-scope": "off"

  # Next.js
  "@next/next/no-img-element": "off"
